LIDAR:
  RECEIVER:
    IP: 192.168.1.106
    PORT: 22
POS:
  RECEIVER:
    COMPORT: COM99
    BAUDRATE: 114514
TRANS:
  IP: 192.168.1.211
  PORT: 1145
PROJECTION:
  LIDAR_TO_IMU:
    YAW: 45
    PITCH: 30
    ROLL: 60
    TRANSLATION: [5, 3, 1]
  CAMERA_TO_IMU:
    YAW: 15
    PITCH: 10
    ROLL: 5
    TRANSLATION: [4, 6, 8]
FLIGHT:
  ALTITUDE: 1000 #